name: Gosec Security Scan

on:
  push:
    branches:
      - foo
  pull_request:
    branches:
      - foo
  schedule:
    # Runs every Sunday at midnight UTC
    - cron: '0 0 * * 0'

jobs:
  security-scan:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      # Step 1: Checkout the repository code
      - name: Checkout Source Code
        uses: actions/checkout@v3

      # Step 2: Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.0' # Specify the Go version you are using

      # Step 3: Install Gosec
      - name: Install Gosec
        run: |
          curl -sfL https://raw.githubusercontent.com/securego/gosec/master/install.sh | sh -s -- -b $(go env GOPATH)/bin

      # Step 4: Run Gosec Security Scanner
      - name: Run Gosec Security Scanner
        run: gosec -no-fail -fmt=sarif -out=results.sarif ./...

      # Step 5: Upload SARIF file for GitHub code scanning
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
